# Generated by Django 5.1.5 on 2025-02-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_book_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_file', models.FileField(upload_to='model_weights')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='link',
        ),
    ]
