# Generated by Django 5.1.5 on 2025-02-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cvmodel_remove_book_author_remove_book_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
