# Generated by Django 5.1.5 on 2025-02-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvmodel',
            name='title',
        ),
    ]
