# Generated by Django 5.1.5 on 2025-02-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_cvmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cam_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
